openapi: 3.0.0
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: app.log
loggers:
  basicLogger:
    level: DEBUG
    handlers: [console, file]
    propogate: no
root:
  level: DEBUG
  handlers: [console]